# Generated by Django 3.0.5 on 2020-12-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_ticker', models.CharField(max_length=20)),
                ('time_executed', models.DateTimeField(verbose_name='time traded')),
                ('trade_type', models.CharField(max_length=20)),
                ('num_shares', models.IntegerField(default=0)),
                ('trade_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
            ],
        ),
    ]
